LUAGUI_NAME = "1fmRandoChests"
LUAGUI_AUTH = "Gicu"
LUAGUI_DESC = "Kingdom Hearts 1FM Randomizer Chests"

local chests_written = false
local chest_values = {
    [0x000] = 0x066E, -- Destiny Islands Chest
    [0x028] = 0x03FE, -- Traverse Town 1st District Candle Puzzle Chest
    [0x02A] = 0x003E, -- Traverse Town 1st District Accessory Shop Roof Chest
    [0x02C] = 0x004E, -- Traverse Town 2nd District Boots and Shoes Awning Chest
    [0x02E] = 0x005E, -- Traverse Town 2nd District Rooftop Chest
    [0x030] = 0x006E, -- Traverse Town 2nd District Gizmo Shop Facade Chest
    [0x032] = 0x007E, -- Traverse Town Alleyway Balcony Chest
    [0x034] = 0x008E, -- Traverse Town Alleyway Blue Room Awning Chest
    [0x036] = 0x009E, -- Traverse Town Alleyway Corner Chest
    [0x03A] = 0x00AE, -- Traverse Town Green Room Clock Puzzle Chest
    [0x03C] = 0x040E, -- Traverse Town Green Room Table Chest
    [0x03E] = 0x00BE, -- Traverse Town Red Room Chest
    [0x040] = 0x041E, -- Traverse Town Mystical House Yellow Trinity Chest
    [0x042] = 0x00CE, -- Traverse Town Accessory Shop Chest
    [0x044] = 0x042E, -- Traverse Town Secret Waterway White Trinity Chest
    [0x046] = 0x033E, -- Traverse Town Geppetto's House Chest
    [0x048] = 0x00DE, -- Traverse Town Item Workshop Right Chest
    [0x050] = 0x00EE, -- Traverse Town 1st District Blue Trinity Balcony Chest
    [0x0B0] = 0x00FE, -- Traverse Town Mystical House Glide Chest
    [0x0B2] = 0x010E, -- Traverse Town Alleyway Behind Crates Chest
    [0x0B4] = 0x011E, -- Traverse Town Item Workshop Left Chest
    [0x0B6] = 0x013E, -- Traverse Town Secret Waterway Near Stairs Chest
    [0x0B8] = 0x074E, -- Wonderland Rabbit Hole Green Trinity Chest
    [0x0BA] = 0x043E, -- Wonderland Rabbit Hole Defeat Heartless 1 Chest
    [0x0BC] = 0x044E, -- Wonderland Rabbit Hole Defeat Heartless 2 Chest
    [0x0BE] = 0x045E, -- Wonderland Rabbit Hole Defeat Heartless 3 Chest
    [0x0C0] = 0x046E, -- Wonderland Bizarre Room Green Trinity Chest
    [0x0C8] = 0x000E, -- Wonderland Queen's Castle Hedge Left Red Chest
    [0x0CA] = 0x001E, -- Wonderland Queen's Castle Hedge Right Blue Chest
    [0x0CC] = 0x002E, -- Wonderland Queen's Castle Hedge Right Red Chest
    [0x0CE] = 0x003E, -- Wonderland Lotus Forest Thunder Plant Chest
    [0x0D0] = 0x004E, -- Wonderland Lotus Forest Through the Painting Thunder Plant Chest
    [0x0D2] = 0x047E, -- Wonderland Lotus Forest Glide Chest
    [0x0D4] = 0x005E, -- Wonderland Lotus Forest Nut Chest
    [0x0D6] = 0x006E, -- Wonderland Lotus Forest Corner Chest
    [0x0D8] = 0x007E, -- Wonderland Bizarre Room Lamp Chest
    [0x0DC] = 0x008E, -- Wonderland Tea Party Garden Above Lotus Forest Entrance 2nd Chest
    [0x0DE] = 0x009E, -- Wonderland Tea Party Garden Above Lotus Forest Entrance 1st Chest
    [0x0E0] = 0x099E, -- Wonderland Tea Party Garden Bear and Clock Puzzle Chest
    [0x0E2] = 0x032E, -- Wonderland Tea Party Garden Across From Bizarre Room Entrance Chest
    [0x0E4] = 0x048E, -- Wonderland Lotus Forest Through the Painting White Trinity Chest
    [0x0F4] = 0x049E, -- Deep Jungle Tree House Beneath Tree House Chest
    [0x0F6] = 0x04AE, -- Deep Jungle Tree House Rooftop Chest
    [0x0F8] = 0x000E, -- Deep Jungle Hippo's Lagoon Center Chest
    [0x0FA] = 0x001E, -- Deep Jungle Hippo's Lagoon Left Chest
    [0x0FC] = 0x002E, -- Deep Jungle Hippo's Lagoon Right Chest
    [0x100] = 0x003E, -- Deep Jungle Vines Chest
    [0x102] = 0x004E, -- Deep Jungle Vines 2 Chest
    [0x104] = 0x005E, -- Deep Jungle Climbing Trees Blue Trinity Chest
    [0x108] = 0x006E, -- Deep Jungle Tunnel Chest
    [0x10A] = 0x04BE, -- Deep Jungle Cavern of Hearts White Trinity Chest
    [0x10C] = 0x007E, -- Deep Jungle Camp Blue Trinity Chest
    [0x10E] = 0x008E, -- Deep Jungle Tent Chest
    [0x110] = 0x009E, -- Deep Jungle Waterfall Cavern Low Chest
    [0x112] = 0x00AE, -- Deep Jungle Waterfall Cavern Middle Chest
    [0x114] = 0x00BE, -- Deep Jungle Waterfall Cavern High Wall Chest
    [0x116] = 0x00CE, -- Deep Jungle Waterfall Cavern High Middle Chest
    [0x118] = 0x072E, -- Deep Jungle Cliff Right Cliff Left Chest
    [0x11A] = 0x073E, -- Deep Jungle Cliff Right Cliff Right Chest
    [0x11C] = 0x075E, -- Deep Jungle Tree House Suspended Boat Chest
    [0x14E] = 0x000E, -- 100 Acre Wood Meadow Inside Log Chest
    [0x150] = 0x04CE, -- 100 Acre Wood Bouncing Spot Left Cliff Chest
    [0x152] = 0x09BE, -- 100 Acre Wood Bouncing Spot Right Tree Alcove Chest
    [0x154] = 0x04DE, -- 100 Acre Wood Bouncing Spot Under Giant Pot Chest
    [0x18A] = 0x000E, -- Agrabah Plaza By Storage Chest
    [0x18C] = 0x001E, -- Agrabah Plaza Raised Terrace Chest
    [0x18E] = 0x04EE, -- Agrabah Plaza Top Corner Chest
    [0x190] = 0x002E, -- Agrabah Alley Chest
    [0x192] = 0x003E, -- Agrabah Bazaar Across Windows Chest
    [0x194] = 0x04FE, -- Agrabah Bazaar High Corner Chest
    [0x196] = 0x004E, -- Agrabah Main Street Right Palace Entrance Chest
    [0x198] = 0x09CE, -- Agrabah Main Street High Above Alley Entrance Chest
    [0x19A] = 0x050E, -- Agrabah Main Street High Above Palace Gates Entrance Chest
    [0x19C] = 0x076E, -- Agrabah Palace Gates Low Chest
    [0x19E] = 0x005E, -- Agrabah Palace Gates High Opposite Palace Chest
    [0x1A0] = 0x006E, -- Agrabah Palace Gates High Close to Palace Chest
    [0x1A2] = 0x051E, -- Agrabah Storage Green Trinity Chest
    [0x1A4] = 0x007E, -- Agrabah Storage Behind Barrel Chest
    [0x1A6] = 0x008E, -- Agrabah Cave of Wonders Entrance Left Chest
    [0x1A8] = 0x009E, -- Agrabah Cave of Wonders Entrance Tall Tower Chest
    [0x1AA] = 0x00AE, -- Agrabah Cave of Wonders Hall High Left Chest
    [0x1AC] = 0x00BE, -- Agrabah Cave of Wonders Hall Near Bottomless Hall Chest
    [0x1AE] = 0x00CE, -- Agrabah Cave of Wonders Bottomless Hall Raised Platform Chest
    [0x1B0] = 0x052E, -- Agrabah Cave of Wonders Bottomless Hall Pillar Chest
    [0x1B2] = 0x053E, -- Agrabah Cave of Wonders Bottomless Hall Across Chasm Chest
    [0x1B4] = 0x00DE, -- Agrabah Cave of Wonders Treasure Room Across Platforms Chest
    [0x1B6] = 0x00EE, -- Agrabah Cave of Wonders Treasure Room Small Treasure Pile Chest
    [0x1B8] = 0x00FE, -- Agrabah Cave of Wonders Treasure Room Large Treasure Pile Chest
    [0x1BA] = 0x010E, -- Agrabah Cave of Wonders Treasure Room Above Fire Chest
    [0x1BC] = 0x011E, -- Agrabah Cave of Wonders Relic Chamber Jump from Stairs Chest
    [0x1BE] = 0x077E, -- Agrabah Cave of Wonders Relic Chamber Stairs Chest
    [0x1C0] = 0x054E, -- Agrabah Cave of Wonders Dark Chamber Abu Gem Chest
    [0x1C2] = 0x012E, -- Agrabah Cave of Wonders Dark Chamber Across from Relic Chamber Entrance Chest
    [0x1C4] = 0x013E, -- Agrabah Cave of Wonders Dark Chamber Bridge Chest
    [0x1C6] = 0x015E, -- Agrabah Cave of Wonders Dark Chamber Near Save Chest
    [0x1C8] = 0x016E, -- Agrabah Cave of Wonders Silent Chamber Blue Trinity Chest
    [0x1CA] = 0x017E, -- Agrabah Cave of Wonders Hidden Room Right Chest
    [0x1CC] = 0x018E, -- Agrabah Cave of Wonders Hidden Room Left Chest
    [0x1CE] = 0x019E, -- Agrabah Aladdin's House Main Street Entrance Chest
    [0x1D0] = 0x01AE, -- Agrabah Aladdin's House Plaza Entrance Chest
    [0x1D2] = 0x09DE, -- Agrabah Cave of Wonders Entrance White Trinity Chest
    [0x25E] = 0x000E, -- Halloween Town Moonlight Hill White Trinity Chest
    [0x260] = 0x001E, -- Halloween Town Bridge Under Bridge
    [0x262] = 0x002E, -- Halloween Town Boneyard Tombstone Puzzle Chest
    [0x264] = 0x003E, -- Halloween Town Bridge Right of Gate Chest
    [0x266] = 0x004E, -- Halloween Town Cemetery Behind Grave Chest
    [0x268] = 0x005E, -- Halloween Town Cemetery By Cat Shape Chest
    [0x26A] = 0x006E, -- Halloween Town Cemetery Between Graves Chest
    [0x26C] = 0x09FE, -- Halloween Town Oogie's Manor Lower Iron Cage Chest
    [0x26E] = 0x007E, -- Halloween Town Oogie's Manor Upper Iron Cage Chest
    [0x270] = 0x008E, -- Halloween Town Oogie's Manor Hollow Chest
    [0x272] = 0x009E, -- Halloween Town Oogie's Manor Grounds Red Trinity Chest
    [0x274] = 0x00AE, -- Halloween Town Guillotine Square High Tower Chest
    [0x276] = 0x00BE, -- Halloween Town Guillotine Square Pumpkin Structure Left Chest
    [0x278] = 0x00CE, -- Halloween Town Oogie's Manor Entrance Steps Chest
    [0x27A] = 0x00DE, -- Halloween Town Oogie's Manor Inside Entrance Chest
    [0x290] = 0x00EE, -- Halloween Town Bridge Left of Gate Chest
    [0x292] = 0x00FE, -- Halloween Town Cemetery By Striped Grave Chest
    [0x294] = 0x010E, -- Halloween Town Guillotine Square Under Jack's House Stairs Chest
    [0x296] = 0x011E, -- Halloween Town Guillotine Square Pumpkin Structure Right Chest
    [0x29A] = 0x000E, -- Olympus Coliseum Coliseum Gates Left Behind Columns Chest
    [0x29C] = 0x001E, -- Olympus Coliseum Coliseum Gates Right Blue Trinity Chest
    [0x29E] = 0x055E, -- Olympus Coliseum Coliseum Gates Left Blue Trinity Chest
    [0x2A0] = 0x056E, -- Olympus Coliseum Coliseum Gates White Trinity Chest
    [0x2A2] = 0x002E, -- Olympus Coliseum Coliseum Gates Blizzara Chest
    [0x2A4] = 0x09AE, -- Olympus Coliseum Coliseum Gates Blizzaga Chest
    [0x1E4] = 0x000E, -- Monstro Chamber 6 Other Platform Chest
    [0x1E6] = 0x001E, -- Monstro Chamber 6 Platform Near Chamber 5 Entrance Chest
    [0x1E8] = 0x057E, -- Monstro Chamber 6 Raised Area Near Chamber 1 Entrance Chest
    [0x1EA] = 0x002E, -- Monstro Chamber 6 Low Chest
    [0x2B6] = 0x027E, -- Monstro Mouth Boat Deck Chest
    [0x2B8] = 0x003E, -- Monstro Mouth High Platform Boat Side Chest
    [0x2BA] = 0x004E, -- Monstro Mouth High Platform Across from Boat Chest
    [0x2BC] = 0x005E, -- Monstro Mouth Near Ship Chest
    [0x2BE] = 0x057E, -- Monstro Mouth Green Trinity Top of Boat Chest
    [0x2C6] = 0x006E, -- Monstro Chamber 2 Ground Chest
    [0x2C8] = 0x007E, -- Monstro Chamber 2 Platform Chest
    [0x2D4] = 0x008E, -- Monstro Chamber 5 Platform Chest
    [0x2D6] = 0x009E, -- Monstro Chamber 3 Ground Chest
    [0x2D8] = 0x00AE, -- Monstro Chamber 3 Platform Above Chamber 2 Entrance Chest
    [0x2DA] = 0x00BE, -- Monstro Chamber 3 Near Chamber 6 Entrance Chest
    [0x2DC] = 0x00CE, -- Monstro Chamber 3 Platform Near Chamber 6 Entrance Chest
    [0x2EA] = 0x028E, -- Monstro Mouth High Platform Near Teeth Chest
    [0x2EC] = 0x00DE, -- Monstro Chamber 5 Atop Barrel Chest
    [0x2EE] = 0x00EE, -- Monstro Chamber 5 Low 2nd Chest
    [0x2F0] = 0x00FE, -- Monstro Chamber 5 Low 1st Chest
    [0x3FA] = 0x09EE, -- Monstro Chamber 6 White Trinity Chest
    [0x2F2] = 0x000E, -- Neverland Pirate Ship Deck White Trinity Chest
    [0x2F4] = 0x0A2E, -- Neverland Pirate Ship Crows Nest Chest
    [0x2F6] = 0x001E, -- Neverland Hold Yellow Trinity Right Blue Chest
    [0x2F8] = 0x006E, -- Neverland Hold Yellow Trinity Left Blue Chest
    [0x2FA] = 0x002E, -- Neverland Galley Chest
    [0x2FC] = 0x078E, -- Neverland Cabin Chest
    [0x2FE] = 0x003E, -- Neverland Hold Flight 1st Chest
    [0x326] = 0x004E, -- Neverland Clock Tower Chest
    [0x328] = 0x005E, -- Neverland Hold Flight 2nd Chest
    [0x32A] = 0x006E, -- Neverland Hold Yellow Trinity Green Chest
    [0x32C] = 0x007E, -- Neverland Captain's Cabin Chest
    [0x32E] = 0x000E, -- Hollow Bastion Rising Falls Water's Surface Chest
    [0x330] = 0x001E, -- Hollow Bastion Rising Falls Under Water 1st Chest
    [0x332] = 0x058E, -- Hollow Bastion Rising Falls Under Water 2nd Chest
    [0x334] = 0x002E, -- Hollow Bastion Rising Falls Floating Platform Near Save Chest
    [0x336] = 0x079E, -- Hollow Bastion Rising Falls Floating Platform Near Bubble Chest
    [0x338] = 0x003E, -- Hollow Bastion Rising Falls High Platform Chest
    [0x33A] = 0x004E, -- Hollow Bastion Castle Gates Gravity Chest
    [0x33C] = 0x059E, -- Hollow Bastion Castle Gates Freestanding Pillar Chest
    [0x33E] = 0x005E, -- Hollow Bastion Castle Gates High Pillar Chest
    [0x340] = 0x006E, -- Hollow Bastion Great Crest Lower Chest
    [0x342] = 0x007E, -- Hollow Bastion Great Crest After Battle Platform Chest
    [0x344] = 0x008E, -- Hollow Bastion High Tower 2nd Gravity Chest
    [0x346] = 0x05AE, -- Hollow Bastion High Tower 1st Gravity Chest
    [0x348] = 0x009E, -- Hollow Bastion High Tower Above Sliding Blocks Chest
    [0x34A] = 0x05BE, -- Hollow Bastion Entrance Hall Left of Emblem Door Chest
    [0x34C] = 0x00AE, -- Hollow Bastion Library Top of Bookshelf Chest
    [0x356] = 0x0A3E, -- Hollow Bastion Lift Stop Library Node After High Tower Switch Gravity Chest
    [0x358] = 0x00FE, -- Hollow Bastion Lift Stop Library Node Gravity Chest
    [0x35A] = 0x0A4E, -- Hollow Bastion Lift Stop Under High Tower Sliding Blocks Chest
    [0x35C] = 0x010E, -- Hollow Bastion Lift Stop Outside Library Gravity Chest
    [0x35E] = 0x012E, -- Hollow Bastion Lift Stop Heartless Sigil Door Gravity Chest
    [0x360] = 0x013E, -- Hollow Bastion Base Level Bubble Under the Wall Platform Chest
    [0x362] = 0x014E, -- Hollow Bastion Base Level Platform Near Entrance Chest
    [0x364] = 0x015E, -- Hollow Bastion Base Level Near Crystal Switch Chest
    [0x366] = 0x07AE, -- Hollow Bastion Waterway Near Save Chest
    [0x368] = 0x0A5E, -- Hollow Bastion Waterway Blizzard on Bubble Chest
    [0x36A] = 0x016E, -- Hollow Bastion Waterway Unlock Passage from Base Level Chest
    [0x36C] = 0x017E, -- Hollow Bastion Dungeon By Candles Chest
    [0x36E] = 0x019E, -- Hollow Bastion Dungeon Corner Chest
    [0x37E] = 0x0A6E, -- Hollow Bastion Grand Hall Steps Right Side Chest
    [0x380] = 0x031E, -- Hollow Bastion Grand Hall Oblivion Chest
    [0x382] = 0x01AE, -- Hollow Bastion Grand Hall Left of Gate Chest
    [0x386] = 0x01BE, -- Hollow Bastion Rising Falls White Trinity Chest
    [0x388] = 0x07BE, -- End of the World Final Dimension 1st Chest
    [0x38A] = 0x07CE, -- End of the World Final Dimension 2nd Chest
    [0x38C] = 0x07DE, -- End of the World Final Dimension 3rd Chest
    [0x38E] = 0x07EE, -- End of the World Final Dimension 4th Chest
    [0x390] = 0x07FE, -- End of the World Final Dimension 5th Chest
    [0x392] = 0x080E, -- End of the World Final Dimension 6th Chest
    [0x394] = 0x081E, -- End of the World Final Dimension 10th Chest
    [0x396] = 0x082E, -- End of the World Final Dimension 9th Chest
    [0x398] = 0x083E, -- End of the World Final Dimension 8th Chest
    [0x39A] = 0x084E, -- End of the World Final Dimension 7th Chest
    [0x39C] = 0x000E, -- End of the World Giant Crevasse 3rd Chest
    [0x39E] = 0x0A8E, -- End of the World Giant Crevasse 5th Chest
    [0x3A0] = 0x001E, -- End of the World Giant Crevasse 1st Chest
    [0x3A2] = 0x0A7E, -- End of the World Giant Crevasse 4th Chest
    [0x3A4] = 0x002E, -- End of the World Giant Crevasse 2nd Chest
    [0x3A6] = 0x087E, -- End of the World World Terminus Traverse Town Chest
    [0x3A8] = 0x088E, -- End of the World World Terminus Wonderland Chest
    [0x3AA] = 0x089E, -- End of the World World Terminus Olympus Coliseum Chest
    [0x3AC] = 0x08AE, -- End of the World World Terminus Deep Jungle Chest
    [0x3AE] = 0x08BE, -- End of the World World Terminus Agrabah Chest
    [0x3B0] = 0x003E, -- End of the World World Terminus Atlantica Chest
    [0x3B2] = 0x08CE, -- End of the World World Terminus Halloween Town Chest
    [0x3B4] = 0x08DE, -- End of the World World Terminus Neverland Chest
    [0x3B6] = 0x004E, -- End of the World World Terminus 100 Acre Wood Chest
    [0x3B8] = 0x08EE, -- End of the World World Terminus Hollow Bastion Chest
    [0x3BA] = 0x005E  -- End of the World Final Rest Chest
}

local function randomize_chests()
    for offset,chest_short in pairs(chest_values) do
        WriteShort(chestTable + offset, chest_short)
    end
end

function _OnInit()
    if GAME_ID == 0xAF71841E and ENGINE_TYPE == "BACKEND" then
        require("VersionCheck")
    else
        ConsolePrint("KH1 not detected, not running script")
    end
end

function _OnFrame()
    if canExecute then
        if seed_vars.chests[0] ~= nil and not chests_written then
            randomize_chests()
        end
    end
end